# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{localized_language_select}
  s.version = File.exist?('VERSION') ? File.read('VERSION') : fail

  s.required_rubygems_version = '>= 1.3.6'
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2011-01-18}
  s.description = %q{Localized language select for Rails 2.3+ with options to control languages to display}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/generators/localized_language_select/import/content_helper.rb",
    "lib/generators/localized_language_select/import_generator.rb",
    "lib/generators/localized_language_select/import/parse_helper.rb",
    "lib/generators/localized_language_select/locales_generator.rb",
    "lib/localized_language_select.rb",
    "lib/localized_language_select/i18n.rb",
    "lib/tasks/localized_language_select_tasks.rake",
    "lib/tasks/yaml_locales_tasks.rake",
    "locale/da.yml",
    "locale/de.yml",
    "locale/en.yml",
    "locale/fr.yml",
    "locale/nl.yml",
    "localized_language_select.gemspec",
    "tasks/localized_language_select_tasks.rake",
    "test/localized_language_select_test.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/localized_language_select}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Localized language select for Rails 4}
  s.test_files = [
    "test/localized_language_select_test.rb"
  ]

  s.add_runtime_dependency(%q<rails>, ['>= 4.1.0'])
  s.add_development_dependency(%q<rspec>, ['>= 2.3.0'])
  s.add_development_dependency(%q<bundler>, ['~> 1.0.0'])
  s.add_development_dependency(%q<jeweler>, ['~> 1.5.2'])
  s.add_development_dependency(%q<rcov>, ['>= 0'])
end

